source 'http://rubygems.org'


gem 'json', '~> 1.8.2'

# scheduler
gem 'whenever', '~> 0.11.0', :require => false


gem 'activesupport', '~> 4.1.2'
gem 'minitest', '~> 5.3.5'
gem 'tzinfo', '~> 1.2.10'
